SatisYonetim/Models/Durum.cs
namespace SatisYonetim.Models
{
    public class Durum
    {
        public int DurumId { get; set; }
        public int DurumSira { get; set; }
        public string DurumAdi { get; set; }
        public virtual ICollection<Teklif> Teklifler { get; set; } = new List<Teklif>();
    }
}

SatisYonetim/Models/DurumViewModel.cs
namespace SatisYonetim.Models
{
    public class DurumViewModel
    {
        public int DurumId { get; set; }
        public string DurumAdi { get; set; }
        public int TeklifId { get; set; }
        public string TeklifAdi { get; set; }
        public string MusteriAdi { get; set; }
        public int Fiyat { get; set; }
    }
}

SatisYonetim/Models/ErrorViewModel.cs
namespace SatisYonetim.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SatisYonetim/Models/Teklif.cs
namespace SatisYonetim.Models
{
    public class Teklif
    {
        public int TeklifId { get; set; }
        public string TeklifAdi { get; set; }
        public string MusteriAdi { get; set; }
        public int Fiyat { get; set; }
        public int DurumId { get; set; }

        //public virtual ICollection<Durum> Durumlar { get; set; }= new List<Durum>();

    }
}

SatisYonetim/Controllers/DurumController.cs
using Microsoft.AspNetCore.Mvc;
using SatisYonetim.Models;
using SatisYonetim.Repositories;

namespace SatisYonetim.Controllers
{
    public class DurumController : Controller
    {
        private readonly DurumRepository _durumRepository;
        public DurumController(DurumRepository durumRepository)
        {
            _durumRepository = durumRepository;
        }
        public IActionResult Index()
        {
            var durumlar = _durumRepository.GetAllDurum();
            return View(durumlar);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Durum durum)
        {
            _durumRepository.Create(durum);
            return RedirectToAction("Index", "Teklif");
        }
        public IActionResult Update(int Id)
        {
            var durum = _durumRepository.GetDurumById(Id);
            if (durum == null)
            {
                return Content("Böyle bir sayfa bulunamadı...");
            }
            return View(durum);
        }
        [HttpPost]
        public IActionResult Update(Durum durum)
        {
            _durumRepository.Update(durum);
            return RedirectToAction("Index", "Teklif");
        }
        public IActionResult Delete(int Id)
        {
            var durum = _durumRepository.GetDurumById(Id);
            if (durum == null)
            {
                return Content("Böyle bir sayfa bulunamadı");
            }
            _durumRepository.Delete(durum);
            return RedirectToAction("Index", "Teklif");
        }
    }
}

SatisYonetim/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SatisYonetim.Models;
using System.Diagnostics;

namespace SatisYonetim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SatisYonetim/Controllers/TeklifController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SatisYonetim.Models;
using SatisYonetim.Repositories;

namespace SatisYonetim.Controllers
{
    public class TeklifController : Controller
    {
        private readonly TeklifRepository _teklifRepository;
        private readonly DurumRepository _durumRepository;
        public TeklifController(TeklifRepository teklifRepository, DurumRepository durumRepository)
        {
            _teklifRepository = teklifRepository;
            _durumRepository = durumRepository;
        }
        public IActionResult Index()
        {

            var teklifler = _teklifRepository.GetAllTeklif();
            var durumlar = _durumRepository.GetAllDurum();


            var modelList = new Tuple<List<Durum>, List<DurumViewModel>>(durumlar, teklifler);

            return View(modelList);
        }
        public IActionResult Delete(int Id)
        {
            var teklif = _teklifRepository.GetTeklifById(Id);
            if (teklif == null)
            {
                return Content("böyle bir sayfa bulunamadı...");
            }
            _teklifRepository.Delete(teklif);
            return RedirectToAction("Index");
        }
        public IActionResult Create()
        {
            var durumListesi = _durumRepository.GetAllDurum();
            var durumSelectList = new SelectList(durumListesi, "DurumId", "DurumAdi");
            ViewBag.DurumListesi = durumSelectList;

            return View();
        }
        [HttpPost]
        public IActionResult Create(DurumViewModel drm)
        {
            _teklifRepository.Create(drm);
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var teklif = _teklifRepository.GetTeklifById(id);

            var durumListesi = _durumRepository.GetAllDurum();
            var durumSelectList = new SelectList(durumListesi, "DurumId", "DurumAdi");
            ViewBag.DurumListesi = durumSelectList;
            return View(teklif);
        }

        [HttpPost]
        public IActionResult Update(DurumViewModel model)
        {

            _teklifRepository.Update(model);
            return RedirectToAction("Index");

        }

    }
}

SatisYonetim/Views/Durum/Create.cshtml
@model Durum

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}
<form method="post" class="col-6">
    <div class="card">
        <div class="card-header bg-warning text-center bg-gradient">Yeni Durum Ekleme</div>
        <div class="card-body">

            <div class="row mb3">
                <label class="form-label">Durum Adı</label>
                <input class="form-control" asp-for="DurumAdi" placeholder="Lütfen Adı Giriniz" required />
            </div>
            <div class="row mb3">
                <label class="form-label">Durum Sırası</label>
                <input class="form-control" asp-for="DurumSira" placeholder="durum sırasını giriniz" required />
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">Add</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>

SatisYonetim/Views/Durum/Index.cshtml
@model List<Durum>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Durum Listesi";

}
<a asp-controller="Durum" asp-action="Create" class="btn btn-outline-success" btn-lg>Durum Ekle</a>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>

            <th>Durumlar</th>
            <th>Sıra</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var durum in Model)
        {
            <tr>
                <td>@durum.DurumAdi</td>
                <td>@durum.DurumSira</td>

                <td>

                    <a onclick="return confirm('Silmek İstediğinize emin misiniz?')" asp-controller="Durum" asp-action="Delete" asp-route-id="@durum.DurumId" class="btn btn-outline-danger">Sil</a>
                    <a onclick="('Güncellemek İstediğinize emin misiniz?)" asp-controller="Durum" asp-action="Update" asp-route-id="@durum.DurumId" class="btn btn-outline-primary">Düzenle</a>

                </td>

            </tr>
        }
    </tbody>
</table>

SatisYonetim/Views/Durum/Update.cshtml
@model Durum

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}
<form asp-action="Update" method="post">
    <input type="hidden" asp-for="DurumId" />
    <div class="form-group">
        <label asp-for="DurumAdi"></label>
        <input asp-for="DurumAdi" class="form-control" />
        <span asp-validation-for="DurumAdi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DurumSira"></label>
        <input asp-for="DurumSira" class="form-control" />
        <span asp-validation-for="DurumSira" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Güncelle</button>
</form>

SatisYonetim/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SatisYonetim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SatisYonetim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SatisYonetim.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SatisYonetim</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SatisYonetim - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SatisYonetim/Views/Teklif/Create.cshtml
@model DurumViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

<form method="post" class="col-6">
    <div class="card">
        <div class="card-header bg-warning text-center bg-gradient">Yeni Durum Ekleme</div>
        <div class="card-body">

            <div class="row mb3">
                <label class="form-label">Teklif Adı</label>
                <input class="form-control" asp-for="TeklifAdi" placeholder="Lütfen Adı Giriniz" required />
            </div>
            <div class="row mb3">
                <label class="form-label">Müşteri ADI</label>
                <input class="form-control" asp-for="MusteriAdi" placeholder="müster adi giriniz" required />
            </div>
            <div class="row mb3">
                <label class="form-label">Fiyat</label>
                <input class="form-control" asp-for="Fiyat" placeholder="fiyatı giriniz" required />
            </div>
            <br />
            <div class="row mb3">
                <label>Durum:</label>
                <select asp-for="DurumAdi" asp-items="@ViewBag.DurumListesi"></select><br />


            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">Add</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>

SatisYonetim/Views/Teklif/Index.cshtml
@model Tuple<List<Durum>, List<DurumViewModel>>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}
<div class="container">
  
    <div class="card">
        <div id="divHeader" class="card-header bg-info text-center bg-gradient">Teklif Listesi</div>
        <div id="divCardBody" class="card-body">
            <a asp-controller="Teklif" asp-action="Create" class="btn btn-outline-success" btn-lg>Teklif Ekle</a>
            <div class="d-flex flex-wrap">
                @foreach (var durumViewModelGroup in Model.Item2.GroupBy(d => d.DurumAdi))
                {
                    <div class="col-md-4 mb-3">
                        <div class="border">
                            <h6 class="d-flex justify-content-between align-items-center">
                                @durumViewModelGroup.Key (@durumViewModelGroup.Sum(d => d.Fiyat))
                            </h6>
                            <table class="table" border="1">
                                <thead>
                                    <tr>
                                        <th>Teklif Adı</th>
                                        <th>Müşteri Adı</th>
                                        <th>Fiyat</th>
                                        <th>İşlemler</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var teklif in durumViewModelGroup)
                                    {
                                        <tr>
                                            <td>@teklif.TeklifAdi</td>
                                            <td>@teklif.MusteriAdi</td>
                                            <td>@teklif.Fiyat</td>
                                            <td>
                                                <a onclick="return confirm('Silmek İstediğinize emin misiniz?')" asp-controller="Teklif" asp-action="Delete" asp-route-id="@teklif.TeklifId" class="btn btn-outline-danger btn-sm">Sil</a>
                                                <a onclick="('Güncellemek İstediğinize emin misiniz?)" asp-controller="Teklif" asp-action="Update" asp-route-id="@teklif.TeklifId" class="btn btn-outline-primary btn-sm">Düzenle</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="col-6">
        <div class="card">
            <div id="divHeader2" class="card-header bg-info text-center bg-gradient">Durum Listesi</div>
            <div id="divCardBody2" class="card-body">
                <a asp-controller="Durum" asp-action="Create" class="btn btn-outline-success" btn-lg>Durum Ekle</a>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Durumlar</th>
                            <th>Sıra</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var durum in Model.Item1)
                        {
                            <tr>
                                <td>@durum.DurumAdi</td>
                                <td>@durum.DurumSira</td>
                                <td>
                                    <a onclick="return confirm('Silmek İstediğinize emin misiniz?')" asp-controller="Durum" asp-action="Delete" asp-route-id="@durum.DurumId" class="btn btn-outline-danger">Sil</a>
                                    <a onclick="('Güncellemek İstediğinize emin misiniz?)" asp-controller="Durum" asp-action="Update" asp-route-id="@durum.DurumId" class="btn btn-outline-primary">Düzenle</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@section Scripts {
    <script>
        $(".alert").slideUp(1).slideDown(1000).slideUp();

        $("#divHeader").click(function () {
            $("#divCardBody").toggle(1500, "swing");
        })
    </script>
    <script>
        $(".alert").slideUp(1).slideDown(1000).slideUp();

        $("#divHeader2").click(function () {
            $("#divCardBody2").toggle(1500, "swing");
        })
    </script>
}

SatisYonetim/Views/Teklif/Update.cshtml
@model DurumViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}
<form method="post" class="col-6">
    <div class="card">
        <div class="card-header bg-warning text-center bg-gradient">Durum Bilgileri Güncelleme</div>
        <div class="card-body">
            <div class="row mb3">
                <input type="hidden" asp-for="TeklifId" />
                <label class="form-label">Teklif adı giriniz</label>
                <input class="form-control" asp-for="TeklifAdi" placeholder="lütfen isim giriniz" required />
                <label class="form-label">Musteradi giriniz</label>
                <input class="form-control" asp-for="MusteriAdi" placeholder="lütfen sıra giriniz" required />
                <label class="form-label">fiyat giriniz</label>
                <input class="form-control" asp-for="Fiyat" placeholder="lütfen sıra giriniz" required />
                <label class="form-label">durumu giriniz</label>
                <select asp-for="DurumAdi" asp-items="@ViewBag.DurumListesi" class="form-control">
                </select>
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">Edit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>